apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer



